"""Backlog CSV generator — converts requirement and feasibility findings into a sorted backlog."""

import csv
import io
import logging
from collections import Counter

from aipm.schemas.findings import Finding

logger = logging.getLogger(__name__)

# Sort orderings
PHASE_ORDER = {"MVP": 0, "V1": 1, "V2": 2}
PRIORITY_ORDER = {"P0": 0, "P1": 1, "P2": 2, "P3": 3}
COMPLEXITY_ORDER = {"simple": 0, "medium": 1, "complex": 2, "epic": 3}

COLUMNS = [
    "epic_id",
    "epic_title",
    "story_id",
    "story_title",
    "description",
    "acceptance_criteria",
    "priority",
    "complexity",
    "phase",
    "labels",
    "dependencies",
]


class BacklogGenerator:
    """Generates a prioritised backlog CSV from requirement and feasibility findings."""

    def generate(
        self,
        requirements_findings: list[Finding],
        feasibility_findings: list[Finding],
        tickets: list | None = None,
    ) -> str:
        """Generate backlog.csv content from requirements and feasibility findings.

        Args:
            requirements_findings: Findings of type 'requirement' with story/epic metadata.
            feasibility_findings: Findings from the feasibility agent with complexity/phase data.
            tickets: Optional list of input TicketItem objects for coverage validation.

        Returns:
            CSV string with header and sorted rows.
        """
        # Build a lookup from feasibility findings keyed by story_id or finding id
        feasibility_map = self._build_feasibility_map(feasibility_findings)

        rows: list[dict[str, str]] = []

        for finding in requirements_findings:
            meta = finding.metadata or {}

            # Only include findings that have story or epic metadata
            if not meta.get("story_id") and not meta.get("epic_id"):
                continue

            story_id = meta.get("story_id", "")
            epic_id = meta.get("epic_id", "")

            # Cross-reference feasibility data
            feas = feasibility_map.get(story_id) or feasibility_map.get(epic_id) or {}

            complexity = feas.get("complexity") or meta.get("complexity", "medium")
            phase = feas.get("phase") or meta.get("phase", "V1")
            dependencies = feas.get("dependencies") or meta.get("dependencies", [])

            acceptance = meta.get("acceptance_criteria", "")
            if isinstance(acceptance, list):
                acceptance = "; ".join(acceptance)

            dep_str = ", ".join(dependencies) if isinstance(dependencies, list) else str(dependencies)

            rows.append(
                {
                    "epic_id": epic_id,
                    "epic_title": meta.get("epic_title", finding.title if epic_id and not story_id else ""),
                    "story_id": story_id,
                    "story_title": meta.get("story_title", finding.title),
                    "description": finding.description,
                    "acceptance_criteria": acceptance,
                    "priority": meta.get("priority", "P2"),
                    "complexity": complexity,
                    "phase": phase,
                    "labels": ", ".join(finding.tags) if finding.tags else "",
                    "dependencies": dep_str,
                }
            )

        # Sort: phase (MVP first) → priority (P0 first) → complexity (simple first)
        rows.sort(
            key=lambda r: (
                PHASE_ORDER.get(r["phase"], 99),
                PRIORITY_ORDER.get(r["priority"], 99),
                COMPLEXITY_ORDER.get(r["complexity"], 99),
            )
        )

        # Post-process: ensure every input ticket has at least one story
        if tickets:
            self._ensure_ticket_coverage(rows, tickets)

        # Post-process: auto-infer dependencies from phase/epic structure
        # when the LLM leaves them empty.  Runs AFTER ticket coverage so stub
        # stories also get dependency chains.
        self._infer_dependencies(rows)

        return self._rows_to_csv(rows)

    def save_csv(self, csv_content: str, output_path: str) -> None:
        """Write CSV content to a file with proper quoting.

        Args:
            csv_content: The CSV string to write.
            output_path: Destination file path.
        """
        with open(output_path, "w", newline="", encoding="utf-8") as f:
            f.write(csv_content)

    def get_stats(self, csv_content: str) -> dict:
        """Return summary statistics from generated CSV content.

        Args:
            csv_content: CSV string previously generated by generate().

        Returns:
            Dict with total_epics, total_stories, stories_per_phase, stories_per_priority.
        """
        reader = csv.DictReader(io.StringIO(csv_content))
        rows = list(reader)

        epics: set[str] = set()
        stories: set[str] = set()
        phase_counter: Counter[str] = Counter()
        priority_counter: Counter[str] = Counter()

        for row in rows:
            if row.get("epic_id"):
                epics.add(row["epic_id"])
            if row.get("story_id"):
                stories.add(row["story_id"])
            phase_counter[row.get("phase", "unknown")] += 1
            priority_counter[row.get("priority", "unknown")] += 1

        return {
            "total_epics": len(epics),
            "total_stories": len(stories),
            "stories_per_phase": dict(phase_counter),
            "stories_per_priority": dict(priority_counter),
        }

    @staticmethod
    def _slugify(text: str) -> str:
        """Convert text to a kebab-case slug suitable for story/epic IDs."""
        import re as _re
        slug = _re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")
        return slug[:60]  # cap length

    def _ensure_ticket_coverage(self, rows: list[dict[str, str]], tickets: list) -> None:
        """Create stub stories for any input tickets not covered by existing rows.

        Scans all row descriptions and story titles for ticket ID references to
        determine coverage.  For any uncovered ticket, appends a minimal row so
        the backlog is never missing an input work-item.
        """
        # Build a set of ticket IDs already mentioned in existing rows.
        # Match by (a) ticket ID text appearing anywhere, or (b) ticket title
        # appearing as a significant substring in the story title/description
        # (case-insensitive, min 4 chars to avoid false positives).
        covered_ids: set[str] = set()
        for row in rows:
            blob = " ".join([
                row.get("description", ""),
                row.get("story_title", ""),
                row.get("story_id", ""),
                row.get("labels", ""),
                row.get("acceptance_criteria", ""),
            ]).upper()
            for ticket in tickets:
                if ticket.id.upper() in blob:
                    covered_ids.add(ticket.id)
                # Also check if the ticket title (≥ 4 chars) is largely contained
                elif len(ticket.title) >= 4:
                    t_words = set(ticket.title.upper().split())
                    # If ≥ 60% of the ticket-title words appear in the row blob, consider covered
                    if t_words and sum(1 for w in t_words if w in blob) / len(t_words) >= 0.6:
                        covered_ids.add(ticket.id)

        # Also check if any requirement finding's source_ids reference the ticket
        # (already captured in labels or description by the LLM usually)

        missing = [t for t in tickets if t.id not in covered_ids]
        if not missing:
            return

        logger.info(
            "Backlog coverage gap: %d/%d tickets missing — generating stub stories for: %s",
            len(missing), len(tickets), ", ".join(t.id for t in missing),
        )

        # Map raw priority labels (CRITICAL, HIGH, etc.) to P0-P3 format
        _PRIORITY_NORMALIZE = {
            "CRITICAL": "P0", "HIGH": "P1", "MEDIUM": "P2", "LOW": "P3",
            "P0": "P0", "P1": "P1", "P2": "P2", "P3": "P3",
        }

        for ticket in missing:
            story_slug = self._slugify(ticket.title)
            # Determine a default epic from the ticket ID prefix (e.g. GROW -> epic-grow)
            prefix = ticket.id.split("-")[0].lower() if "-" in ticket.id else "backlog"
            epic_id = f"epic-{prefix}"
            raw_priority = (ticket.priority or "").upper()
            priority = _PRIORITY_NORMALIZE.get(raw_priority, "P2")

            rows.append({
                "epic_id": epic_id,
                "epic_title": f"{prefix.upper()} Initiatives",
                "story_id": f"story-{story_slug}",
                "story_title": ticket.title,
                "description": ticket.description,
                "acceptance_criteria": "",
                "priority": priority,
                "complexity": "medium",
                "phase": "V1",
                "labels": ", ".join(ticket.labels) if ticket.labels else ticket.id,
                "dependencies": "",
            })

    @staticmethod
    def _infer_dependencies(rows: list[dict[str, str]]) -> None:
        """Auto-infer story dependencies from phase and epic structure.

        Rules applied (only when a story has no explicit dependencies):
        - A V1 story depends on all MVP stories in the same epic.
        - A V2 story depends on all V1 stories in the same epic.
        - If no same-epic predecessor exists, fall back to all stories in the
          prior phase (cross-epic), preventing isolated stories.
        """
        # Index stories by (epic_id, phase)
        epic_phase_stories: dict[tuple[str, str], list[str]] = {}
        for row in rows:
            sid = row.get("story_id", "")
            eid = row.get("epic_id", "")
            phase = row.get("phase", "")
            if sid:
                epic_phase_stories.setdefault((eid, phase), []).append(sid)

        phase_predecessors = {"V1": "MVP", "V2": "V1"}

        for row in rows:
            # Skip if already has explicit dependencies
            if row.get("dependencies", "").strip():
                continue

            phase = row.get("phase", "")
            epic_id = row.get("epic_id", "")
            prior_phase = phase_predecessors.get(phase)
            if not prior_phase:
                continue  # MVP stories have no predecessor phase

            # Prefer same-epic predecessors, fall back to all prior-phase stories
            deps = epic_phase_stories.get((epic_id, prior_phase), [])
            if not deps:
                # Collect all stories in the prior phase across all epics
                deps = [
                    sid
                    for (eid, ph), sids in epic_phase_stories.items()
                    if ph == prior_phase
                    for sid in sids
                ]

            if deps:
                row["dependencies"] = ", ".join(deps)

    def _build_feasibility_map(self, feasibility_findings: list[Finding]) -> dict[str, dict]:
        """Build a lookup of feasibility data keyed by story/epic ID."""
        fmap: dict[str, dict] = {}
        for finding in feasibility_findings:
            meta = finding.metadata or {}
            key = meta.get("story_id") or meta.get("epic_id") or finding.id
            fmap[key] = {
                "complexity": meta.get("complexity"),
                "phase": meta.get("phase"),
                "dependencies": meta.get("dependencies", []),
            }
        return fmap

    def _rows_to_csv(self, rows: list[dict[str, str]]) -> str:
        """Convert row dicts to a CSV string."""
        output = io.StringIO()
        writer = csv.DictWriter(output, fieldnames=COLUMNS, quoting=csv.QUOTE_ALL)
        writer.writeheader()
        writer.writerows(rows)
        return output.getvalue()
