"""Backlog CSV generator — converts requirement and feasibility findings into a sorted backlog."""

import csv
import io
from collections import Counter

from aipm.schemas.findings import Finding

# Sort orderings
PHASE_ORDER = {"MVP": 0, "V1": 1, "V2": 2}
PRIORITY_ORDER = {"P0": 0, "P1": 1, "P2": 2, "P3": 3}
COMPLEXITY_ORDER = {"simple": 0, "medium": 1, "complex": 2, "epic": 3}

COLUMNS = [
    "epic_id", "epic_title", "story_id", "story_title", "description",
    "acceptance_criteria", "priority", "complexity", "phase", "labels", "dependencies",
]


class BacklogGenerator:
    """Generates a prioritised backlog CSV from requirement and feasibility findings."""

    def generate(
        self,
        requirements_findings: list[Finding],
        feasibility_findings: list[Finding],
    ) -> str:
        """Generate backlog.csv content from requirements and feasibility findings.

        Args:
            requirements_findings: Findings of type 'requirement' with story/epic metadata.
            feasibility_findings: Findings from the feasibility agent with complexity/phase data.

        Returns:
            CSV string with header and sorted rows.
        """
        # Build a lookup from feasibility findings keyed by story_id or finding id
        feasibility_map = self._build_feasibility_map(feasibility_findings)

        rows: list[dict[str, str]] = []

        for finding in requirements_findings:
            meta = finding.metadata or {}

            # Only include findings that have story or epic metadata
            if not meta.get("story_id") and not meta.get("epic_id"):
                continue

            story_id = meta.get("story_id", "")
            epic_id = meta.get("epic_id", "")

            # Cross-reference feasibility data
            feas = feasibility_map.get(story_id) or feasibility_map.get(epic_id) or {}

            complexity = feas.get("complexity") or meta.get("complexity", "medium")
            phase = feas.get("phase") or meta.get("phase", "V1")
            dependencies = feas.get("dependencies") or meta.get("dependencies", [])

            acceptance = meta.get("acceptance_criteria", "")
            if isinstance(acceptance, list):
                acceptance = "; ".join(acceptance)

            dep_str = ", ".join(dependencies) if isinstance(dependencies, list) else str(dependencies)

            rows.append({
                "epic_id": epic_id,
                "epic_title": meta.get("epic_title", finding.title if epic_id and not story_id else ""),
                "story_id": story_id,
                "story_title": meta.get("story_title", finding.title),
                "description": finding.description,
                "acceptance_criteria": acceptance,
                "priority": meta.get("priority", "P2"),
                "complexity": complexity,
                "phase": phase,
                "labels": ", ".join(finding.tags) if finding.tags else "",
                "dependencies": dep_str,
            })

        # Sort: phase (MVP first) → priority (P0 first) → complexity (simple first)
        rows.sort(key=lambda r: (
            PHASE_ORDER.get(r["phase"], 99),
            PRIORITY_ORDER.get(r["priority"], 99),
            COMPLEXITY_ORDER.get(r["complexity"], 99),
        ))

        return self._rows_to_csv(rows)

    def save_csv(self, csv_content: str, output_path: str) -> None:
        """Write CSV content to a file with proper quoting.

        Args:
            csv_content: The CSV string to write.
            output_path: Destination file path.
        """
        with open(output_path, "w", newline="", encoding="utf-8") as f:
            f.write(csv_content)

    def get_stats(self, csv_content: str) -> dict:
        """Return summary statistics from generated CSV content.

        Args:
            csv_content: CSV string previously generated by generate().

        Returns:
            Dict with total_epics, total_stories, stories_per_phase, stories_per_priority.
        """
        reader = csv.DictReader(io.StringIO(csv_content))
        rows = list(reader)

        epics: set[str] = set()
        stories: set[str] = set()
        phase_counter: Counter[str] = Counter()
        priority_counter: Counter[str] = Counter()

        for row in rows:
            if row.get("epic_id"):
                epics.add(row["epic_id"])
            if row.get("story_id"):
                stories.add(row["story_id"])
            phase_counter[row.get("phase", "unknown")] += 1
            priority_counter[row.get("priority", "unknown")] += 1

        return {
            "total_epics": len(epics),
            "total_stories": len(stories),
            "stories_per_phase": dict(phase_counter),
            "stories_per_priority": dict(priority_counter),
        }

    def _build_feasibility_map(self, feasibility_findings: list[Finding]) -> dict[str, dict]:
        """Build a lookup of feasibility data keyed by story/epic ID."""
        fmap: dict[str, dict] = {}
        for finding in feasibility_findings:
            meta = finding.metadata or {}
            key = meta.get("story_id") or meta.get("epic_id") or finding.id
            fmap[key] = {
                "complexity": meta.get("complexity"),
                "phase": meta.get("phase"),
                "dependencies": meta.get("dependencies", []),
            }
        return fmap

    def _rows_to_csv(self, rows: list[dict[str, str]]) -> str:
        """Convert row dicts to a CSV string."""
        output = io.StringIO()
        writer = csv.DictWriter(output, fieldnames=COLUMNS, quoting=csv.QUOTE_ALL)
        writer.writeheader()
        writer.writerows(rows)
        return output.getvalue()
